planner_server:
  ros__parameters:
    planner_plugins: ["GridBased2", "GridBased1"]
    use_sim_time: False

    GridBased1:
      plugin: "nav2_smac_planner::SmacPlannerHybrid"
      minimum_turning_radius: 2.0

    GridBased2:
      plugin: "nav2_smac_planner::SmacPlannerHybrid"
      minimum_turning_radius: 0.02

global_costmap:
  global_costmap:
    ros__parameters:
      plugins: ["static_layer", "inflation_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 3.0
        cost_scaling_factor: 3.
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: false
        subscribe_to_updates: true  
        map_topic: "/map"
        map_update_topic: "/map_update"
